import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DM_Sans } from "next/font/google";

import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

// const generalSans = localFont({
//   src: [
//     {
//       path: "./fonts/GeneralSans-Medium.woff2",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "./fonts/GeneralSans-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "./fonts/GeneralSans-SemiBold.woff2",
//       weight: "600",
//       style: "normal",
//     },
//     {
//       path: "./fonts/GeneralSans-Bold.woff2",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-general-sans",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-gray-50 w-full pt-[20px] pb-[150px] lg:pt-[50px] lg:pb-[100px] ${dmSans.className}`}
      >
        <div className="w-[90vw] lg:max-w-4xl mx-auto border border-gray-300 rounded-2xl px-2 py-4 lg:px-[40px] lg:py-[30px]">
          <Header />
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
